const data = [
  {
    id: 1,
    img: "https://ca-times.brightspotcdn.com/dims4/default/3fb0882/2147483647/strip/true/crop/6547x4365+0+0/resize/1200x800!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F0f%2F13%2F298e9d214fe5a3e978318636384c%2F3084280-sd-me-beach-cleanup-hl-003.jpg",
    name: "Ocean Cleanup",
    date: "10th Feb 2024",
    type: "Workshop",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing",
    location: "Chong Pang",
    spots: 4,
  },
  {
    id: 2,
    img: "https://www.pacificangelshomecare.com/wp-content/uploads/2022/07/comparing-different-types-of-elder-care-services.jpg",
    name: "Elder Care",
    date: "30th March 2024",
    type: "Training",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing",
    location: "Serangoon",
    spots: 5,
  },
  {
    id: 3,
    img: "https://assets.simpleviewinc.com/simpleview/image/upload/c_fill,h_800,q_75,w_1200/v1/clients/durangoco/MANNA18_17_16_36_eff1ab49-871a-4de2-ab66-dd5772ea0b19.jpg",
    name: "Soup Kitchen",
    date: "18th Sep 2024",
    type: "Workshop",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing",
    location: "Aljunied",
    spots: 2,
  },
  {
    id: 4,
    img: "https://www.muktahealthcare.com/images/gallery/16266812527.jpg",
    name: "Nursing Home",
    date: "7th August 2024",
    type: "Workshop",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing wadsfa",
    location: "Keat Hong Camp",
    spots: 8,
  },
  {
    id: 5,
    img: "https://www.marlboroughcollegemalaysia.org/wp-content/uploads/2022/01/OutreachBCU2022-1-1.jpg",
    name: "Beach Cleanup",
    date: "4th August 2024",
    type: "Workshop",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing wadsfa",
    location: "Keat Hong Camp",
    spots: 8,
  },
  {
    id: 6,
    img: "https://watermark.lovepik.com/photo/20211130/large/lovepik-housekeeping-staff-cleans-the-desktop-picture_501265219.jpg",
    name: "Housekeeping",
    date: "27th June 2024",
    type: "Training",
    isFavourite: false,
    description: "lorem ipsum dolor sit amet, consectetur adipiscing wadsfa",
    location: "Keat Hong Camp",
    spots: 8,
  },
];

export default data;
